### ISSUE TITLE
Bug Report: Gas Used not matching the explorer

### ISSUE THREAD

**Issue by forgxyz** [MetricsDAO/harmony_dbt#133]
Flipside user has reported that the gas used is not matching what Harmony explorer shows.

Example tx: `0x6efe00fc988884b9c5cc97960716e28aa4ec2743a23c851c8d5ff46270dfb33d`

<img width="272" alt="Screenshot 2022-07-06 at 10 29 32 AM" src="https://user-images.githubusercontent.com/58153492/177634443-ad315deb-daf8-46b6-9c0a-233de003da4e.png">
<img width="744" alt="Screenshot 2022-07-06 at 10 29 41 AM" src="https://user-images.githubusercontent.com/58153492/177634445-e8d2575a-e925-4287-80d9-1a90c303d4ab.png">

**Comment by eevui** [comment]
I'd like to pick this up.

Cursory peek at it, it's because the model uses the cumulative gas field of the receipts. Understandably, it could be read as the cumulative gas used for the entire transaction. However, this actually refers to the cumulative gas used for the entire block.

I'll write up a new query to account for this and will submit a PR later on.
