### ISSUE TITLE
[Table] ViperSwap Add / Remove Liquidity

### ISSUE THREAD

**Issue by antonyip** [MetricsDAO/harmony_dbt#58]

**Comment by RplusT** [comment]
Hi @antonyip !
I'd like to take this on if that's okay. Here's my proposed schema:

| log_id                                                             | block_id | block_timestamp         | tx_hash                                                            | liquidity_provider                         | action           | pool_address                               | pool_name    | token0                                     | token0_symbol | token0_name | token1                                     | token1_symbol | token1_name | amount0_raw         | amount0_adjusted | amount1_raw            | amount1_adjusted | amount0_usd | amount1_usd |
|--------------------------------------------------------------------|----------|-------------------------|--------------------------------------------------------------------|--------------------------------------------|------------------|--------------------------------------------|--------------|--------------------------------------------|---------------|-------------|--------------------------------------------|---------------|-------------|---------------------|------------------|------------------------|------------------|-------------|-------------|
| 0xe5746f06f639437f0809d76096aeb10607c41d1d343c46a85ef2618b6052c067 | 20745838 | 2021-12-20 23:40:23.000 | 0xe5746f06f639437f0809d76096aeb10607c41d1d343c46a85ef2618b6052c067 | 0x42299973c42b40bef8ae4a8cdf6c973944853c39 | add_liquidity    | 0xf170016d63fb89e1d559e8f87a17bcc8b7cd9c00 | 1USDC-WONE   | 0x985458e523db3d53125813ed68c274899e9dfab4 | 1USDC         | USD Coin    | 0xcf664087a5bb0237a0bad6742852ec6c8d69a27a | WONE          | Wrapped ONE | 827172735           | 827.172735       | 3477875362481779507200 | 3477.875362482   | 827.172735  | 800.739918  |
| 0xcde300c72377e09115d5b492b61a5cd264140a86c68596e47c8d4c1ead067c67 | 20745889 | 2021-12-20 23:42:09.000 | 0xcde300c72377e09115d5b492b61a5cd264140a86c68596e47c8d4c1ead067c67 | 0x208a70c70ad1727644aee4a0f889ffb48c070ea1 | remove_liquidity | 0xd42913e79469fae403055560c08611cf66907b01 | 1SUSHI-VIPER | 0xbec775cb42abfa4288de81f387a9b1a3c4bc552a | NULL          | NULL        | 0xea589e93ff18b1a1f1e9bac7ef3e86ab62addc79 | NULL          | NULL        | 1928218828085470700 | NULL             | 9202464146712277000    | NULL             | NULL        | NULL        |

Just a few notes:
1. Since this schema relies on the `tokens` table, there will be some NULL values for the token names and symbols because from what I understand, the `tokens` table does not contain all the HRC20 tokens (#38 , #92 ). However, the token addresses (`token0`, `token1`) won't be blank since I'll be using the `txs` table to fill in that data (as seen on line 2 of the sample schema).

2. For the same reason, some `amount_adjusted` and `amount_usd` values will be NULL since those would rely on the `decimals` in the `tokens` table. Hence why I have the `amount_raw` columns in the sample so there will still be data on the liquidity.

Let me know if this is okay. 😄

**Comment by antonyip** [comment]
> e09115d5b492

Sorry I took so long to get back to you. Looks good to me. Please carry on with the other steps :)

**Comment by RplusT** [comment]
@antonyip no worries! Ready now for your review #100 :)
